### ISSUE TITLE
Max number of connections

### ISSUE THREAD

**Issue by roundrobin** [DazWorrall/flask-sse#5]
How much eventsource clients where you able to connect on one flask-see instance?

I am right now evaluating different backend servers for EventSource. I was able to connect > 3000 clients through a node.js backend and send very stable messages to them. But 3000 seems very small to me, if I compare that with other protocols (mqtt, websockets) i tested.

What are the limits you experienced?

**Comment by DazWorrall** [comment]
This is quite a late reply but as I mention in the readme, I never got to use this in production so don't have any numbers for you I'm afraid.
