### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pypingou** [DazWorrall/flask-sse#7]
Thanks for this handy little project, but nowhere is mentioned the license of the code. Could you make it explicit?

**Comment by DazWorrall** [comment]
Done, MIT

**Comment by pypingou** [comment]
Btw, did you receive the agreement of all the contributors to license their work?

FOSS is both splendid and quite annoying when dealing with the legal aspects of things.

I would advice to ask @insom and @machow to publicly (potentially here) agree with licensing their contribution under the MIT license.\

Thanks :)

**Comment by insom** [comment]
+1 MIT

On Tuesday, 13 October 2015, Pierre-Yves Chibon <notifications@github.com>
wrote:

> Btw, did you receive the agreement of all the contributors to license
> their work?
>
> FOSS is both splendid and quite annoying when dealing with the legal
> aspects of things.
>
> I would advice to ask @insom <https://github.com/insom> and @machow
> <https://github.com/machow> to publicly (potentially here) agree with
> licensing their contribution under the MIT license.\
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DazWorrall/flask-sse/issues/7#issuecomment-147693468>.
>


-- 
Aaron Brady

www.iweb.co.uk
aaron@iweb.co.uk
T: +44 (0) 1785 279 920

**
** For technical support and hosting queries please contact:
**
** help@iweb.co.uk / 0845 00 66 528
**

**Comment by machow** [comment]
I'm fine with licensing my contribution under the MIT license.

**Comment by pypingou** [comment]
We're all good then, thanks everyone \ó/
